spring.application.name=Journal-App


spring.datasource.url=jdbc:mysql://avnadmin:AVNS_c16F-vr3gXlhdZagYM-@mysql-fae7eae-ononeofyourown.d.aivencloud.com:28300/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_c16F-vr3gXlhdZagYM-


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true